version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  post_build:
    commands:
      - mvn clean package
      - mv target/sneaker_inventory_management_api-1.0-SNAPSHOT.war sneaker_inventory_management_api-1.0-SNAPSHOT.war
artifacts:
  files:
    - sneaker_inventory_management_api-1.0-SNAPSHOT.war
    - .ebextensions/**/*

